<?xml version="1.0" encoding="UTF-8"?>
<testrun name="Rerun at.chainlet.rse.core.RudimentaryStackVM_Test.pollNextTerm_ShouldExecuteTermAsWordIfItsInTheLibrary" project="RSE" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testcase name="pollNextTerm_ShouldExecuteTermAsWordIfItsInTheLibrary" classname="at.chainlet.rse.core.RudimentaryStackVM_Test" time="0.004">
    <error>java.lang.IllegalArgumentException
	at at.chainlet.rse.core.RudimentaryStackVM.parseValueAndPutItOnStack(RudimentaryStackVM.java:130)
	at at.chainlet.rse.core.RudimentaryStackVM.pollNextTerm(RudimentaryStackVM.java:112)
	at at.chainlet.rse.core.RudimentaryStackVM.parse(RudimentaryStackVM.java:96)
	at at.chainlet.rse.core.RudimentaryStackVM_Test.pollNextTerm_ShouldExecuteTermAsWordIfItsInTheLibrary(RudimentaryStackVM_Test.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

</error>
  </testcase>
</testrun>
